spring.application.name=demo



server.port=${PORT:8080}

server.address=0.0.0.0

# H2 DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.security.user.name=admin
spring.security.user.password=admin
app.frontend.url=https://budgetapp-rwo4.vercel.app
openai.api.key=${OPENAI_API_KEY}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leman.memmedli31378@gmail.com
spring.mail.password=vvkstqnzndynrlcz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
