spring.application.name=demo


server.port=${PORT}

server.address=0.0.0.0

# H2 DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.hibernate.ddl-auto=update



spring.jpa.show-sql=true
spring.jpa.open-in-view=false
app.frontend.url=https://budgetapp-7bzf.vercel.app
app.support.inbox=${SUPPORT_INBOX_EMAIL:leman.memmedli31378@gmail.com}
openai.api.key=${OPENAI_API_KEY}
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=${EMAIL_FROM}
